#!/bin/bash

# Excepciones
EXCEPCION[0]='co'
EXCEPCION[1]='us'
EXCEPCION[2]='ca'

# Creamos la lista de IPSET
ipset -N permitido hash:net -exist

# Eliminamos las zonas descargadas anteriormente
echo "Eliminando zonas descargadas anteriormente..."
rm -f /tmp/all-zones.tar.gz
rm -f /tmp/all-zones.tar.gz.*
rm -f /tmp/*.zone

# Descargamos la zona
echo "Descargando Zonas..."
for i in "${EXCEPCION[@]}";
do
	echo "Descargando zona $i"
        wget -P /tmp/ http://www.ipdeny.com/ipblocks/data/countries/$i.zone
done

# Agregamos las zonas de los paises
echo "Agregando Zonas..."
echo "Esto puede tardar unos minutos..."
find /tmp/ -type f -name "*.zone" | awk {'print "for i in $(cat " $1 "); do ipset -A permitido $i; done"'} | bash
