#!/bin/bash

# Excepciones
EXCEPCION="co"

# Creamos la lista de IPSET
ipset -N internacional hash:net
ipset flush internacional

# Eliminamos las zonas descargadas anteriormente
echo "Eliminando zonas previas"
rm -f /tmp/all-zones.tar.gz
rm -f /tmp/all-zones.tar.gz.*
rm -f /tmp/*.zone

# Descargamos la zona
echo "Descargando nuevas zonas"
wget -P /tmp/ http://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz

# Descomprimimos
tar xzf /tmp/all-zones.tar.gz -C /tmp/

# Agregamos las zonas de los paises
echo "Agregando nuevas zonas..."
echo "Esto puede tardar unos minutos..."
find /tmp/ -type f -name "*.zone" | grep -v $EXCEPCION | awk {'print "for i in $(cat " $1 "); do ipset -A internacional $i; done"'} | bash
