#!/bin/bash

# Flush de reglas
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

# Politicas por defecto
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

# Bloqueos de Direcciones IP
lastb | awk {'print $3'} | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort | uniq | awk {'print "iptables -A INPUT -s " $1 " -j DROP"'} | bash

# Limites de conexiones
iptables -A INPUT -p TCP --syn --dport 80 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 443 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 8080 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 22 -m connlimit --connlimit-above 2 -j REJECT
