#!/bin/bash

# Flush de reglas
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

# Politicas por defecto
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

# Revision paquetes SYN
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

# Revision paquetes Fragmentados
iptables -A INPUT -f -j DROP

# Revision paquetes XMAS
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

# Revision paquetes NULL
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

# ICMP
iptables -A INPUT -s 192.168.0.0/24 -p ICMP -m limit --limit 2/second --limit-burst 2 -j ACCEPT
iptables -A INPUT -s 192.168.1.0/24 -p ICMP -m limit --limit 2/second --limit-burst 2 -j ACCEPT
iptables -A INPUT -p ICMP --icmp-type echo-request -j REJECT

# Direcciones Permitidas
iptables -A INPUT -i lo -j ACCEPT		#(Local)
iptables -A INPUT -s 192.168.0.0/24 -j ACCEPT	#(Rango Claro)
iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT	#(Rango TP-Link)
iptables -A INPUT -s 190.145.6.158 -j ACCEPT	#(Oficina)
iptables -A INPUT -s www.ipdeny.com -j ACCEPT 	#(IP Deny - Bloqueo Paises)

# Bloqueos de Direcciones IP
lastb | awk {'print $3'} | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort | uniq | awk {'print "iptables -A INPUT -s " $1 " -j DROP"'} | bash

# Bloqueos de Paises
ipset -N permitido hash:net -exist
iptables -A INPUT -p TCP -m set --match-set permitido src -j ACCEPT
iptables -A INPUT -p UDP -m set --match-set permitido src -j ACCEPT
iptables -A INPUT -p TCP -m set ! --match-set permitido src -j DROP
iptables -A INPUT -p UDP -m set ! --match-set permitido src -j DROP

# Limites de conexiones
iptables -A INPUT -p TCP --syn --dport 80 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 443 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 8080 -m connlimit --connlimit-above 30 -j REJECT
iptables -A INPUT -p TCP --syn --dport 22 -m connlimit --connlimit-above 2 -j REJECT
